#pragma once

#include <vector>
#include <string>

enum SCRIPT_TYPE
{
	ANIMCONTROLLER,
	ATTSCRIPT,
	BASICTEXTSCRIPT,
	BLOCKSCRIPT,
	BOSSCAMERASCRIPT,
	BOSSHPUISCRIPT,
	BRAD,
	CONTROLLERSCRIPT,
	CUTSCENECAMERASCRIPT,
	ELEVATORSCRIPT,
	ENEMYATTSCRIPT,
	ENEMYCONTROLLER,
	ENEMYSCRIPT,
	GAMECAMERASCRIPT,
	HITSCRIPT,
	LEVELSELECTSCRIPT,
	MAINCAMERASCRIPT,
	MOUSECOLLIDERSCRIPT,
	PLAYERATTSCRIPT,
	PLAYERHPTEXT,
	PLAYERHPUISCRIPT,
	PLAYERSCRIPT,
	PROJECTILESCRIPT,
	TESTSCRIPT,
	TEXTSCRIPT,
	TITLEMENUSCRIPT,
	UICAMERASCRIPT,
	UNITSCRIPT,
	WORKMAN,
	WORKWOMAN,
	END,
};

using namespace std;

class CScript;

class CScriptMgr
{
public:
	static void GetScriptInfo(vector<wstring>& _vec);
	static CScript * GetScript(const wstring& _strScriptName);
	static CScript * GetScript(UINT _iScriptType);
	static const wchar_t * GetScriptName(CScript * _pScript);
};
